# This is a Github workflow file dedicated for Github platform alone.
name: 'Render LaTeX document'
description: 'a Github action script for rendering LaTex document'
author: 'sentient-codebot'
# inputs:
#   class_option:
#     description: class option for the document class to be compiled
#     required: true
inputs:
  run:
    description: commands to run in texlive
    required: true
outputs:
  time:
    description: 'Time when rendering is completed.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.run }}
  entrypoint: /bin/bash
    
branding:
  icon: book
  color: green
